# Generated by Django 4.2.3 on 2023-11-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data1',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='data2',
            new_name='Name',
        ),
    ]
